services:
  posterproof087:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: posterproof087
    labels:
      - traefik.enable=true
      - traefik.http.routers.posterproof087.rule=Host(`posterproof087.colmena.dev`)
      - traefik.http.routers.posterproof087.entrypoints=websecure
      - traefik.http.routers.posterproof087.tls.certresolver=letsencrypt
      - traefik.http.services.posterproof087.loadbalancer.server.port=9876
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:9876/__/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    name: dokploy-network
    external: true
